Fix #24 and removed #
tessel/accel-mma84 pull request #26
Opened 2017-07-03 10:45 UTC by brihijoshi

Added spaces in the titles for appropriate Markdown titles and removed # for * in the bullet points.

2017-07-03 15:19 UTC, HipsterBrown approved these changes

2017-07-03 22:14 UTC, Frijol commented
fixes https://github.com/tessel/accel-mma84/issues/24

2017-07-03 22:15 UTC, Frijol requested changes

2017-07-03 22:15 UTC, Frijol commented on README.md
> +* &#x20;<a href="#api-accel-availableScaleRanges-Logs-the-available-accelerometer-ranges-in-units-of-Gs" name="api-accel-availableScaleRanges-Logs-the-available-accelerometer-ranges-in-units-of-Gs"><
Leave `#` formatting please! See note in RFID repo

2017-07-04 18:14 UTC, Frijol approved these changes

2017-07-04 18:14 UTC, merged